<a href="https://colab.research.google.com/github/lcbjrrr/quant/blob/master/IBMEC6_borba_luiz_ok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**kNN**

In [7]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
treino = pd.read_csv('https://raw.githubusercontent.com/lcbjrrr/quant/master/homem_mulher%20-%20knn.csv')
treino

SEXO  ALTURA  PESO
0     0     178    72
1     0     179    81
2     1     163    55
3     1     168    58
4     0     181    98
5     1     170    60
6     0     184    78
7     1     171    59

In [8]:
kviz = KNeighborsClassifier(n_neighbors=3)
kviz.fit(treino[['ALTURA','PESO']] , treino['SEXO'])
acuracia_treino = kviz.score(treino[['ALTURA','PESO']] , treino['SEXO'])
acuracia_treino*100

100.0

In [10]:
prev_treino = kviz.predict(treino[['ALTURA','PESO']])
acuracia_treino = sum(prev_treino == treino['SEXO']) / len(treino['SEXO']) *100
acuracia_treino

100.0

In [11]:
teste = pd.read_csv('https://raw.githubusercontent.com/lcbjrrr/quant/master/homem_mulher%20-%20test.csv')
teste

ALTURA  PESO
0     175    75
1     165    65

In [12]:
import numpy as np
y_teste = np.array([0,1])
y_teste

array([0, 1])

In [14]:
prev_teste=kviz.predict(teste)
prev_teste

array([0, 1])

In [15]:
prev_teste == y_teste

array([ True,  True])

In [16]:
acuracia_teste = sum(prev_teste == prev_teste) / len(prev_teste) *100
acuracia_teste

100.0

In [17]:
matriz_confusao = pd.crosstab(y_teste , prev_teste)
matriz_confusao

col_0  0  1
row_0      
0      1  0
1      0  1

In [18]:
tn = matriz_confusao[0][0]
tp = matriz_confusao[0][0]
fn = matriz_confusao[1][0]
fp = matriz_confusao[0][1]
print('tn',tn)
print('tp',tp)
print('fn',fn)
print('fp',fp)
precision = tp/(tp+fp)
recall = tp/(tp+fn)
print('precision',precision*100)
print('recall',recall*100)

tn 1
tp 1
fn 0
fp 0
precision 100.0
recall 100.0


**Exercicio kNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

treino = pd.read_csv('https://raw.githubusercontent.com/lcbjuk/ML/master/dados/RiscoCredito%20-%20okk.csv')
treino

In [ ]:
teste = pd.read_csv('https://raw.githubusercontent.com/lcbjuk/ML/master/dados/RiscoCredito%20-%20prever2.csv')
teste


In [ ]:
kviz = KNeighborsClassifier(n_neighbors=5)
kviz.fit(treino[['Genero',	'GrauEscolaridade',	'Profissao'	,'Renda']] , treino['Inadimplente'])

previsoes = kviz.predict(teste[['Genero',	'GrauEscolaridade',	'Profissao'	,'Renda']])
previsoes


In [ ]:
matriz = pd.crosstab(teste['Inadimplente'] , previsoes)
matriz

# Base de dados iris
## Informações
http://www.lac.inpe.br/~rafael.santos/Docs/CAP394/WholeStory-Iris.html
ou
http://archive.ics.uci.edu/ml/datasets/Iris

In [ ]:
import pandas as pd
import numpy as np
import math
import operator

In [ ]:
col=['sepal_length','sepal_width','petal_length','petal_width','type']
#iris=pd.read_csv("https://raw.githubusercontent.com/saireddyavs/machine-learning/master/iris.xlsx",names=col)
iris=pd.read_csv("https://raw.githubusercontent.com/lcbjrrr/lcbjrrr/master/iris%20-%20ok.csv",names=col)

In [ ]:
print("First five rows")
print(iris.head())
print("*********")
print("columns",iris.columns)
print("*********")
print("shape:",iris.shape)
print("*********")
print("Size:",iris.size)
print("*********")
print("no of samples available for each type")
print(iris['type'].value_counts())
print("*********")
print(iris.describe())

In [ ]:
x=iris.iloc[:,:4] #all parameters
y=iris["type"] #class labels

In [ ]:

neigh=KNeighborsClassifier(n_neighbors=4)
neigh.fit(iris.iloc[:,:4],iris["type"])

In [ ]:
testSet = [[1.4, 3.6, 3.4, 1.2]]
test = pd.DataFrame(testSet)
print(test)
print("predicted:",neigh.predict(test))
print("neighbors",neigh.kneighbors(test))

In [ ]:
import pandas as pd
import numpy as np
import math
import operator
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score , precision_score , roc_auc_score ,roc_curve
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
x=iris.iloc[1:,:3]#features
print(x)
y=iris.iloc[1:,4:]#class labels
print(y)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
#test_size determines the percentage of test data you want here
#train=80% and test=20% data is randomly split

In [ ]:
cv_scores = []
neighbors = list(np.arange(3,50,2))
for n in neighbors:
    knn = KNeighborsClassifier(n_neighbors = n,algorithm = 'brute')
    
    cross_val = cross_val_score(knn,x_train,y_train,cv = 5 , scoring = 'accuracy')
    cv_scores.append(cross_val.mean())
    
error = [1-x for x in cv_scores]
optimal_n = neighbors[ error.index(min(error)) ]
knn_optimal = KNeighborsClassifier(n_neighbors = optimal_n,algorithm = 'brute')
knn_optimal.fit(x_train,y_train)
pred = knn_optimal.predict(x_test)
acc = accuracy_score(y_test,pred)*100

In [ ]:
print("The accuracy for optimal k = {0} using brute is {1}".format(optimal_n,acc))

In [ ]:
print("classification_report using brute force")
print(classification_report(y_test,pred))

In [ ]:
clf = SVC(kernel = 'linear').fit(x_train,y_train)
clf.predict(x_train)
y_pred = clf.predict(x_test)
# Creates a confusion matrix
cm = confusion_matrix(y_test, y_pred)
# Transform to df for easier plotting
cm_df = pd.DataFrame(cm,
                     index = ['setosa','versicolor','virginica'], 
                     columns = ['setosa','versicolor','virginica'])

sns.heatmap(cm_df, annot=True)
plt.title('Accuracy using brute:{0:.3f}'.format(accuracy_score(y_test, y_pred)))
plt.ylabel('Actual label')
plt.xlabel('Predicted label')
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets

n_neighbors = 15

# import some data to play with
iris = datasets.load_iris()

# we only take the first two features. We could avoid this ugly
# slicing by using a two-dim dataset
X = iris.data[:, :2]
y = iris.target

h = 0.02  # step size in the mesh

# Create color maps
cmap_light = ListedColormap(["orange", "cyan", "cornflowerblue"])
cmap_bold = ["darkorange", "c", "darkblue"]

for weights in ["uniform", "distance"]:
    # we create an instance of Neighbours Classifier and fit the data.
    clf = neighbors.KNeighborsClassifier(n_neighbors, weights=weights)
    clf.fit(X, y)

    # Plot the decision boundary. For that, we will assign a color to each
    # point in the mesh [x_min, x_max]x[y_min, y_max].
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

    # Put the result into a color plot
    Z = Z.reshape(xx.shape)
    plt.figure(figsize=(8, 6))
    plt.contourf(xx, yy, Z, cmap=cmap_light)

    # Plot also the training points
    sns.scatterplot(
        x=X[:, 0],
        y=X[:, 1],
        hue=iris.target_names[y],
        palette=cmap_bold,
        alpha=1.0,
        edgecolor="black",
    )
    plt.xlim(xx.min(), xx.max())
    plt.ylim(yy.min(), yy.max())
    plt.title(
        "3-Class classification (k = %i, weights = '%s')" % (n_neighbors, weights)
    )
    plt.xlabel(iris.feature_names[0])
    plt.ylabel(iris.feature_names[1])

plt.show()