<a href="https://colab.research.google.com/github/lcbjrrr/quant/blob/master/J_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Topic:** AI/ML

**Title:** Neural Network (with Flux)

**Author:** Luiz Barboza

**Date:** 20/dec/22

**Lang:** Julia

**Site:** https://quant-research.group/

**Email:** contato@quant-research.group


# Julia Installation

In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.8.3" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia BenchmarkTools"
JULIA_PACKAGES_IF_GPU="CUDA" # or CuArrays for older Julia versions
JULIA_NUM_THREADS=2
#---------------------------------------------------#

if [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  nvidia-smi -L &> /dev/null && export GPU=1 || export GPU=0
  if [ $GPU -eq 1 ]; then
    JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"' &> /dev/null
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.8.3 on the current Colab Runtime...
2023-01-05 21:16:00 URL:https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.3-linux-x86_64.tar.gz [130030846/130030846] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...
Installing Julia package BenchmarkTools...
Installing IJulia kernel...
[ Info: Installing julia kernelspec in /root/.local/share/jupyter/kernels/julia-1.8

Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then
jump to the 'Checking the Installation' section.


In [ ]:
versioninfo()

Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 2 × AMD EPYC 7B12
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver2)
  Threads: 2 on 2 virtual cores
Environment:
  LD_LIBRARY_PATH = /usr/local/nvidia/lib:/usr/local/nvidia/lib64
  LD_PRELOAD = /usr/lib/x86_64-linux-gnu/libtcmalloc.so.4
  JULIA_NUM_THREADS = 2


# Neural Networks (with Flux)

In [ ]:
import Pkg
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("Lathe") 
Pkg.add("Flux") 
Pkg.add("StatsBase") 
Pkg.add("EvalMetrics") 

using CSV
using DataFrames
using Lathe
using Lathe.preprocess: TrainTestSplit
using Flux
using Flux: crossentropy, throttle
using StatsBase
using EvalMetrics

## NN - Classification

In [ ]:
;wget https://raw.githubusercontent.com/lcbjrrr/data/main/banking%20-%20train.csv


In [ ]:
;wget https://raw.githubusercontent.com/lcbjrrr/data/main/banking%20-%20tests.csv

In [ ]:
train=CSV.read("banking - train.csv", DataFrame)
first(train,5)

5×3 DataFrame
 Row │ salary   balance  default 
     │ Float64  Float64  Int64   
─────┼───────────────────────────
   1 │  1000.0    100.0        0
   2 │   950.0     95.0        0
   3 │   800.0     85.0        0
   4 │  1100.0   5500.0        0
   5 │   999.0   6000.0        0

In [ ]:
test=CSV.read("banking - tests.csv", DataFrame)
first(train,5)

5×3 DataFrame
 Row │ salary   balance  default 
     │ Float64  Float64  Int64   
─────┼───────────────────────────
   1 │  1000.0    100.0        0
   2 │   950.0     95.0        0
   3 │   800.0     85.0        0
   4 │  1100.0   5500.0        0
   5 │   999.0   6000.0        0

In [68]:
X_train  = transpose(hcat([ row.salary for row in eachrow(train)],[ row.balance for row in eachrow(train)]))
y_train = transpose([row.default for row in eachrow(train)])
y_train

1×16 transpose(::Vector{Int64}) with eltype Int64:
 0  0  0  0  0  0  0  0  0  1  1  1  0  0  0  0

In [ ]:
EP = 20
N=length(y_train)
BS=floor(Int,N/EP)
data = Flux.Data.DataLoader((X_train, y_train), batchsize=BS,shuffle=true);
nn    = Chain(
  Dense(2,4, relu),
  Dense(4,3, relu),
  Dense(3,1,identity),
  softmax
  ) 
loss(x, y) = Flux.Losses.binarycrossentropy(nn(x), y)
for i in 1:EP
    # train (loss func, NN params, data/batches, optimizer)
    Flux.train!(loss, Flux.params(nn), data,ADAM())
end
pred_train  =  transpose([nn(X_train[i:i+1])[1] for i in 1:2:N*2])
pred_train

1×16 transpose(::Vector{Float64}) with eltype Float64:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [ ]:
function accuracy(y,pred)
  acc = sum(pred.==y)/length(y)
  return acc
end

acc_train = accuracy(y_train, pred_train)
print("Acc. Train: ",acc_train)

Acc. Train: 0.1875

In [69]:
X_test = transpose(hcat([ row.salary for row in eachrow(test)],[ row.balance for row in eachrow(test)]))
y_test = transpose([row.default for row in eachrow(test)])
print(y_test)


[1 0 0 0 0 0 0 1 0 1]

In [70]:
pred_test  =  transpose([ Int64(nn(X_test[i:i+1])[1]) for i in 1:2:length(y_test)*2])
print(pred_test)

[1 1 1 1 1 1 1 1 1 1]

In [71]:
acc_test = accuracy(y_test, pred_test)
print("Acc. Test: ",acc_test)

Acc. Test: 0.3

In [72]:
counts( y_test,pred_test)

2×1 Matrix{Int64}:
 7
 3

In [74]:
println("Precision: ",precision(vec(y_test),vec(pred_test)) )
println("Recall: " , recall(vec(y_test),vec(pred_test)) )

Precision: 0.3
Recall: 1.0


# Second Example: Gender

In [ ]:
;wget https://raw.githubusercontent.com/lcbjrrr/data/main/gender%20-%20all.csv

In [76]:
df=CSV.read("gender - all.csv", DataFrame)
first(df,5)

5×3 DataFrame
 Row │ G      H        W        
     │ Int64  Float64  Float64  
─────┼──────────────────────────
   1 │     0  187.571  109.952
   2 │     0  174.706   73.7775
   3 │     0  188.24    96.7004
   4 │     0  182.197  100.019
   5 │     0  177.5     93.7954

In [ ]:
train, test = TrainTestSplit(df,.70)

In [78]:
X_train  = transpose(hcat([ row.H for row in eachrow(train)],[ row.W for row in eachrow(train)]))
y_train = transpose([row.G for row in eachrow(train)])
y_train

1×6968 transpose(::Vector{Int64}) with eltype Int64:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  1  1  1  1  1  1  1  1  1  1  1  1

In [79]:
EP = 20
N=length(y_train)
BS=floor(Int,N/EP)
data = Flux.Data.DataLoader((X_train, y_train), batchsize=BS,shuffle=true);
nn    = Chain(
  Dense(2,4, relu),
  Dense(4,3, relu),
  Dense(3,1,identity),
  softmax
  ) 
loss(x, y) = Flux.Losses.binarycrossentropy(nn(x), y)
for i in 1:EP
    # train (loss func, NN params, data/batches, optimizer)
    Flux.train!(loss, Flux.params(nn), data,ADAM())
end
pred_train  =  transpose([nn(X_train[i:i+1])[1] for i in 1:2:N*2])
pred_train

1×6968 transpose(::Vector{Float64}) with eltype Float64:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [80]:
function accuracy(y,pred)
  acc = sum(pred.==y)/length(y)
  return acc
end

acc_train = accuracy(y_train, pred_train)
print("Acc. Train: ",acc_train)

Acc. Train: 0.5086107921928817

In [84]:
X_test = transpose(hcat([ row.H for row in eachrow(test)],[ row.W for row in eachrow(test)]))
y_test = transpose([row.G for row in eachrow(test)])

pred_test  =  transpose([ Int64(nn(X_test[i:i+1])[1]) for i in 1:2:length(y_test)*2])


1×3032 transpose(::Vector{Int64}) with eltype Int64:
 1  1  1  1  1  1  1  1  1  1  1  1  1  …  1  1  1  1  1  1  1  1  1  1  1  1

In [85]:
acc_test = accuracy(y_test, pred_test)
print("Acc. Test: ",acc_test)

Acc. Test: 0.48021108179419525

In [86]:
counts( y_test,pred_test)

2×1 Matrix{Int64}:
 1576
 1456

In [87]:
println("Precision: ",precision(vec(y_test),vec(pred_test)) )
println("Recall: " , recall(vec(y_test),vec(pred_test)) )

Precision: 0.48021108179419525
Recall: 1.0




```
X_train  = [ [row.H,row.W] for row in eachrow(train)]
y_train = [ row.G for row in eachrow(train)]
batches = (Flux.batch(X_train),Flux.batch(y_train))
nn = Chain(
  Dense(2,4, relu),
  Dense(4,3, relu),
  Dense(3,1,identity),
  softmax
  )
L(x,y)=Flux.crossentropy(nn(x), y)
evalcb = () -> @show(L) 
for i in 1:11
  Flux.train!(L,Flux.params(nn),[batches],ADAM(), cb = Flux.throttle(evalcb, 1))
end
pred_train  = [ nn(row[1]) for row in eachrow(X_train)]

```





```
 
#Auxiliary functions for generating our data
function generate_real_data(n)
    x1 = rand(1,n) .- 0.5
    x2 = (x1 .* x1)*3 .+ randn(1,n)*0.1
    return vcat(x1,x2)
end
function generate_fake_data(n)
    θ  = 2*π*rand(1,n)
    r  = rand(1,n)/3
    x1 = @. r*cos(θ)
    x2 = @. r*sin(θ)+0.5
    return vcat(x1,x2)
end
# Creating our data
train_size = 5000
real = generate_real_data(train_size)
fake = generate_fake_data(train_size)
# Visualizing
scatter(real[1,1:500],real[2,1:500])
scatter!(fake[1,1:500],fake[2,1:500])
function NeuralNetwork()
    return Chain(
            Dense(2, 25,relu),
            Dense(25,1,x->σ.(x))
            )
end
# Organizing the data in batches
X    = hcat(real,fake)

Y    = vcat(ones(train_size),zeros(train_size))

data = Flux.Data.DataLoader((X, Y'), batchsize=100,shuffle=true);
# Defining our model, optimization algorithm and loss function
m    = NeuralNetwork()
opt = Descent(0.05)
loss(x, y) = sum(Flux.Losses.binarycrossentropy(m(x), y))
# Training Method 1
ps = Flux.params(m)
epochs = 20
for i in 1:epochs
    Flux.train!(loss, ps, data, opt)
end
println(mean(m(real)),mean(m(fake))) # Print model prediction
# Visualizing the model predictions
scatter(real[1,1:100],real[2,1:100],zcolor=m(real)')
scatter!(fake[1,1:100],fake[2,1:100],zcolor=m(fake)',legend=false)

```

