<a href="https://colab.research.google.com/github/lcbjrrr/quant/blob/master/Matrizes_elementares_e_resolu%C3%A7%C3%A3o_de_sistemas_lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ficha Técnica

Disciplina - Algebra linear e Processos Dinâmicos.

Conteúdo - 
- Representação matricial
- Operações com linhas em matrizes.
- Matrizes elementares

Autores: 
- Anderson Borba (anderson.aborba@professores.ibmec.edu.br) e
- Luiz Barboza (luiz.cbjunior@professores.ibmec.edu.br).

Endereço eletrônico: http://quant-ibmec.group/calculos/

# Sistema linear na forma matricial:
\begin{equation}\nonumber
    \left[
    \begin{array}{cccc}
        a_{11}& a_{12}& \cdots& a_{1n} \\
        a_{21}& a_{22}& \cdots& a_{2n} \\
        \vdots & \vdots&  &\vdots \\
        a_{m1}& a_{m2}& \cdots& a_{mn} \\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        x_1 \\
        x_2 \\
        \vdots \\
        x_n \\
    \end{array}
    \right]=
    \left[
    \begin{array}{c}
        b_1 \\
        b_2 \\
        \vdots \\
        b_n \\
    \end{array}
    \right]
\end{equation}
Podemos escrever $Ax=b$.

Exemplo: Resolver o sistema liner $Ax=b$:
\begin{equation}\nonumber
    \left[
    \begin{array}{ccccc}
        1& 1& 2& 2 & 1 \\
        2& 2& 4& 4 & 3 \\
        2& 2& 4& 4 & 2 \\
        3& 5& 8& 6 & 5 \\
    \end{array}
    \right]
    \left[
    \begin{array}{c}
        x_1 \\
        x_2 \\
        x_3 \\
        x_4 \\
        x_5 \\
    \end{array}
    \right]=
    \left[
    \begin{array}{c}
         1\\
         1\\
         2\\
         3\\
    \end{array}
    \right]
\end{equation}
Escrevendo o sistema linear de forma extendida,
\begin{equation}\nonumber
    \left[
    \begin{array}{rrrrr|r}
         1&  1&  2& 2&1& 1\\
         2&  2&  4& 4&3& 1\\
         2&  2&  4& 4&2& 2\\
         3&  5& 8& 6&5& 3\\
     \end{array}
\right]
\end{equation}     

# Matriz elementar
Matriz elementar é igual a matriz identidade exceto na posicão $E_{i,j}$. Nessa posição vamos inserir o multiplicador proveniente da operação com linhas.

Assim, a matriz elementar $E$ resulta de efetuar uma certa operação sobre linhas na matriz $A_{n}$ $n\times n$, então o produto $EA$ é uma matriz que resulta da operações por linhas.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

A = np.array([[1.,1.,2.,2.,1.,1.],[2.,2.,4.,4.,3.,1.],[2.,2.,4.,4.,2.,2.],[3.,5.,8.,6.,5.,3.]])
print(A)

[[1. 1. 2. 2. 1. 1.]
 [2. 2. 4. 4. 3. 1.]
 [2. 2. 4. 4. 2. 2.]
 [3. 5. 8. 6. 5. 3.]]


Definindo a operação $L_2=>L_2-\frac{a_{21}}{a_{11}}L_1$, isto é, $L_2=>L_2-\frac{2}{1}L_1$

In [ ]:
E1 = np.array([[1,0,0,0],[-2,1,0,0],[0,0,1,0],[0,0,0,1]])
print(E1)

[[ 1  0  0  0]
 [-2  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]


In [ ]:
E1 @ A

array([[ 1.,  1.,  2.,  2.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1., -1.],
       [ 2.,  2.,  4.,  4.,  2.,  2.],
       [ 3.,  5.,  8.,  6.,  5.,  3.]])

Definindo a operação $L_3=>L_3-\frac{a_{31}}{a_{11}}L_1$, isto é, $L_3=>L_3-\frac{2}{1}L_1$

In [ ]:
E2 = np.array([[1,0,0,0],[0,1,0,0],[-2,0,1,0],[0,0,0,1]])
print(E2)

[[ 1  0  0  0]
 [ 0  1  0  0]
 [-2  0  1  0]
 [ 0  0  0  1]]


In [ ]:
E2@E1@A


array([[ 1.,  1.,  2.,  2.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  5.,  8.,  6.,  5.,  3.]])

Definindo a operação $L_4=>L_4-\frac{a_{41}}{a_{11}}L_1$, isto é, $L_4=>L_4-\frac{3}{1}L_1$

In [ ]:
E3 = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[-3,0,0,1]])
print(E3)

[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [-3  0  0  1]]


In [ ]:
E3@E2@E1@A

array([[ 1.,  1.,  2.,  2.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  2.,  0.,  2.,  0.]])

Temos que trocar a linha 2 pela linha 4 da matriz, para isso vamos definir a matriz elementar que trocas as linhas.

In [ ]:
E4 = np.array([[1,0,0,0],[0,0,0,1],[0,0,1,0],[0,1,0,0]])
print(E4)

[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]


In [ ]:
E4@E3@E2@E1@A

array([[ 1.,  1.,  2.,  2.,  1.,  1.],
       [ 0.,  2.,  2.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1.]])

Temos que trocar a linha 3 pela linha 4 da matriz, para isso vamos definir a matriz elementar que trocas as linhas.

In [ ]:
E5 = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
print(E5)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [ ]:
E5@E4@E3@E2@E1@A

array([[ 1.,  1.,  2.,  2.,  1.,  1.],
       [ 0.,  2.,  2.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

Assim descobrimos uma matriz equivalente triangular superior(Escalonada).

In [ ]:
U = E5@E4@E3@E2@E1@A
print(U)

[[ 1.  1.  2.  2.  1.  1.]
 [ 0.  2.  2.  0.  2.  0.]
 [ 0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  0.]]


Pergunta: Será que é possível escrever $A=LU$? Cenas para o próximo notebook!!!!!

# Referências
- Anton, Howard Rorres, Chris. Álgebra Linear com Aplicações. Editora Bookman - 2012.
- Carl D, Meyer, Matrix Analysis and Applied Linear Algebra, Editora SIAM - 2000  
- https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/solving-linear-systems/