<a href="https://colab.research.google.com/github/lcbjrrr/quant/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


#Vetor/Array


In [ ]:
import numpy as np

a1 = [1, 2, 3]
print(a1)
a2 = np.array([1, 2, 3])   
print(a2)

[1, 2, 3]
[1 2 3]


# 2D

In [ ]:
b = np.array( [ [1,2,3],
                [4,5,6] ] )   
print(b)

print(b.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


#Acessando

In [ ]:
# Opcao usual de acesso
print(b[1,1])

# Outra opcao de acesso
print(b[1][1])

5
5


#Outras Inicializacoes

In [ ]:
zero2_2 = np.zeros( (2,2) )
print(zero2_2)

[[0. 0.]
 [0. 0.]]


In [ ]:
ones3_3 = np.ones( (3,3) )
print(ones3_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Slicing


In [ ]:
a = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])
print(a)

fatia = a[2:3,0:4]
print('FATIA')
print(fatia)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
FATIA
[[ 9 10 11 12]]


#Query

In [ ]:
a = np.array([[1,2], 
              [3, 4], 
              [5, 6]])
print(a)
print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[3 4 5 6]




# Soma (elemento a elemento)


In [ ]:
x = np.array([1,2])
y = np.array([5,6])
z = x + y
print(z)

[6 8]


In [ ]:
# atente que com lista nao funciona
x = [1,2]
y = [5,6]
z = x + y
print(z)

[1, 2, 5, 6]


# Subtracao (elemento a elemento)


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = x - y
print(z)

[[-4 -4]
 [-4 -4]]


# Divisao (elemento a elemento)


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = x / y
print(z)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


# Multiplacacao (elemento a elemento)


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = x * y
print(z)

[[ 5 12]
 [21 32]]


# Multiplacacao DE MATRIZES


In [ ]:
notas = np.array([ [7,8,9],
                   [5,6,7],
                   [5,5,5],
                   [9,9,9] ])
pesos = np.array([ [0.4],
                   [0.4],
                   [0.2] ])

medias = notas @ pesos 

print(notas)
print(notas.shape)
print(pesos)
print(pesos.shape)
print(medias)

[[7 8 9]
 [5 6 7]
 [5 5 5]
 [9 9 9]]
(4, 3)
[[0.4]
 [0.4]
 [0.2]]
(3, 1)
[[7.8]
 [5.8]
 [5. ]
 [9. ]]


In [ ]:
# note que...
medias = pesos @ notas 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-6d2011f25ab2> in <module>()
      1 # note que...
----> 2 medias = pesos @ notas

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature <br> (n?,k),(k,m?)->(n?,m?) (size 4 is different from 1)

In [ ]:
print(pesos)
print(pesos.shape)
print(notas)
print(notas.shape)

# Transposta

In [ ]:
pesos_t = pesos.T
print(pesos_t)
print(pesos_t.shape)

[[0.4 0.4 0.2]]
(1, 3)


In [ ]:
notas_t = notas.T
print(notas_t)
print(notas_t.shape)

[[7 5 5 9]
 [8 6 5 9]
 [9 7 5 9]]
(3, 4)


In [ ]:
# agora...
medias = pesos_t @ notas_t 
print(medias)

[[7.8 5.8 5.  9. ]]


#Funcoes

In [ ]:
import numpy as np

notas = np.array([ [7,8,9],
                   [5,6,7],
                   [5,5,5],
                   [9,9,9] ])
pesos = np.array([ [0.4],
                   [0.4],
                   [0.2] ])

medias = notas @ pesos 
print(medias)
print(medias[medias>7])
notas[notas>=9]

[[7.8]
 [5.8]
 [5. ]
 [9. ]]
[7.8 9. ]


array([9, 9, 9, 9])

In [ ]:
media = medias.mean()
desv = medias.std()
menor = medias.cumin()
maior = medias.max()
soma = medias.sum()

print(media)
print(desv)
print(menor)
print(maior)
print(soma)


6.9
1.5842979517754858
5.0
9.0
27.6
