<a href="https://colab.research.google.com/github/lcbjrrr/quant/blob/master/Um_modelo_de_crescimento_e_consumo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ficha Técnica

Disciplina

- Álgebra linear e processos dinâmicos.

Conteúdo 

- Autovalores e autovetores.

Aplicação 

- Modelo de crescimento e consumo. 

- Linguagem de programação (Python).

Autores: 
- Anderson Borba (anderson.aborba@professores.ibmec.edu.br) e

- Luiz Barboza (luiz.cbjunior@professores.ibmec.edu.br).

Endereço eletrônico: http://quant-ibmec.group/

# Modelo de crescimento e consumo
Considere uma economia com n setores que produzem n bens denotados pelo vetor $\mathbf{x}$. Todos os bens são utilizadas como insumos na produção e consumidas pelos trabalhadores.

- Os requisitos de entrada de bens na produção são dados por uma matriz $A$ $n\times n$ entrada/saída. 

- Os requisitos de mão-de-obra são dados por um vetor linha $\mathbf{a}$ mão-de-obra/saída. (OBS: Observe que todos os elementos de $A$ e $\mathbf{a}$ são não-negativos). 

- Supõe-se que a cesta de consumo dos trabalhadores é dada pelo vetor linha c. (Esta pode ser interpretado como uma cesta salarial que reflete o salário mínimo social, determinado por condições sociais e históricas da sociedade em questão).

Este sistema de produção e seu uso pode ser resumido da seguinte forma:

Output = entrada de produção requerida + consumo (dos trabalhadores), ou

\begin{equation}
\begin{aligned}
x= Ax + c^T a \cdot x.
\end{aligned}\tag{Economia sem crescimento}
\end{equation}

Esta economia utiliza toda produção e consumo corrente, portanto, ela é incapaz de crescer. Agora vamos introduzir o crescimento neste quadro.

Por uma questão de simplicidade, suponhamos que os formuladores de políticas públicas tenham como objetivo o crescimento de todos os setores em uma mesma taxa, ou seja, em uma "direção de crescimento equilibrado". Portanto, a quantidade extra de bens
necessário para ter crescimento é dado por:
\begin{equation}
\begin{aligned}
s= g(Ax + c^T a \cdot x).
\end{aligned}\tag{Fator de crescimento}
\end{equation}

Onde g é a taxa de crescimento equilibrado (um escalar) da economia. 

Considerando o sistema de produção,
\begin{equation}
\begin{aligned}
x= Ax + c^T a \cdot x + s,\\
x= Ax + c^T a \cdot x + g(Ax + c^T a \cdot x).
\end{aligned}\tag{Economia com crescimento}
\end{equation}
Onde o primeiro termo corresponde aos requisitos de entrada para consumo atual e o segundo termo significa os requisitos de entrada para o crescimento.

Realizando a álgebra necessária:
\begin{equation}
\begin{aligned}
x= (A + c^T a) x + g(A + c^T a) x,\\
x= (1 + g)(A + c^T a)x\\
\frac{1}{(1 + g)}x = (A + c^T a) x.\\
\end{aligned}
\end{equation}

Vamos definir
\begin{equation}
\begin{aligned}
B = (A + c^T a),\\
\end{aligned}
\end{equation}
e 
\begin{equation}
\begin{aligned}
\lambda = \frac{1}{1+g}.\\
\end{aligned}
\end{equation}
Onde b é a "matriz de entrada aumentada", ou seja, que leva em conta as necessidades de consumo da mão-de-obra, e trata esta última como um insumo da produção. E $\lambda$ definimos como autovalores.

Portanto, podemos reescrever
\begin{equation}
\begin{aligned}
\lambda x = B x.\\
\end{aligned}\tag{Equação matricial}
\end{equation}


Pergunta 1. Suponhamos que os formuladores de políticas gostariam de saber a taxa de crescimento máxima viável para esta economia? Sendo dado a tecnologia $(A, \mathbf{a})$ e exogenamente o vetor $\mathbf{c}$ representa a cesta de consumo dos trabalhadores.

Podemos responder da seguinte maneira: Note que o sistema de equações matriciais pode ser reescrito como
\begin{equation}
\begin{aligned}
\lambda x - B x = 0.\\
(\lambda I - B) x = 0.\\
\end{aligned}\tag{Auto-sistema}
\end{equation}
onde $I$ é a matriz de identidade $n\times n$ e $0$ é o vetor $n\times 1$ zero.

A partir do auto-sistema a resposta a pergunta acima pode ser obtida encontrando os autovalores e autovetores correspondentes da matriz B. Neste contexto, um sistema de produção é viável se ao menos puder se sustentar, ou seja, se o autovalor for não negativo.

# Exemplo numérico de uma economia
Suponha que a tecnologia da economia é dada pela seguinte entrada/saída matriz $A$, e mão-de-obra/saída pelo vetor $\mathbf{a}$
\begin{equation}
    A= \left[
    \begin{array}{ccc}
       0.120 &0.170 &0.120 \\
       0.140 &0.110 &0.140  \\
       0.110 &0.130 &0.110  \\
    \end{array}
    \right]
\end{equation}
\begin{equation}
        {\bf a} = 
    \left[
    \begin{array}{c}
        0.36 \\
        0.37\\
        0.40 \\
    \end{array}
    \right]
\end{equation}
E o vetor de consumo $\mathbf{c}$,
\begin{equation}
        {\bf c} = 
    \left[
    \begin{array}{c}
        0.6 \\
        0.45\\
        0.45 \\
    \end{array}
    \right]
\end{equation}


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

A = np.array([[0.120,0.170,0.120],[0.140,0.110,0.140],[0.110,0.130,0.110]])
a = np.array([[0.36,0.37,0.40]])
c = np.array([[0.6,0.45,0.45]])
print(A)
print(a)
print(c)

[[0.12 0.17 0.12]
 [0.14 0.11 0.14]
 [0.11 0.13 0.11]]
[[0.36 0.37 0.4 ]]
[[0.6  0.45 0.45]]


In [ ]:
CA= np.matmul(np.transpose(c), a)
print(CA)

[[0.216  0.222  0.24  ]
 [0.162  0.1665 0.18  ]
 [0.162  0.1665 0.18  ]]


In [ ]:
B = A + CA
print(B)
from numpy import linalg as la
lambdas, v = la.eig(B)
print('Autovalores de B\n',lambdas)
print('Autovetores de B\n', v)
g1 = (1 - lambdas[0]) / lambdas[0] * 100
g2 = (1 - lambdas[1]) / lambdas[1] * 100
g3 = (1 - lambdas[2]) / lambdas[2] * 100
print('Taxa percentual de crecimento:',g1)
print('Taxa percentual de crecimento:',g2)
print('Taxa percentual de crecimento:',g3)

[[0.336  0.392  0.36  ]
 [0.302  0.2765 0.32  ]
 [0.272  0.2965 0.29  ]]
Autovalores de B
 [ 9.45510680e-01 -2.82176429e-04 -4.27285032e-02]
Autovetores de B
 [[-0.65767447 -0.71353561  0.63710354]
 [-0.54541702 -0.03069231 -0.75554924]
 [-0.51960039  0.69994637  0.1524612 ]]
Taxa percentual de crecimento: 5.762951333327542
Taxa percentual de crecimento: -354488.21183808125
Taxa percentual de crecimento: -2440.3581308470866


Dos autovalores da matriz B apenas o primeiro é positivo. Portanto, os outros não têm significado econômico. Tecnicamente a taxa de crescimento máxima viável para esta economia é 5.7 porcento no período considerado.

Pergunta 2. Esta economia pode permitir um aumento de 10% no bem de consumo dos trabalhadores?

In [ ]:
c1 = np.array([[0.70,0.55,0.55]])
CA1= np.matmul(np.transpose(c1), a)
B1 = A + CA1
print(B1)
from numpy import linalg as la
lambdas1, v1 = la.eig(B1)
print('Autovalores de B\n',lambdas1)
print('Autovetores de B\n',v1)
g11 = (1 - lambdas1[0]) / lambdas1[0] * 100
g12 = (1 - lambdas1[1]) / lambdas1[1] * 100
g13 = (1 - lambdas1[2]) / lambdas1[2] * 100 
print('Taxa percentual de crecimento:',g11)
print('Taxa percentual de crecimento:',g12)
print('Taxa percentual de crecimento:',g13)

[[0.372  0.429  0.4   ]
 [0.338  0.3135 0.36  ]
 [0.308  0.3335 0.33  ]]
Autovalores de B
 [ 1.05842281e+00 -1.28049597e-04 -4.27947592e-02]
Autovetores de B
 [[-0.64959866 -0.71532095  0.63776239]
 [-0.54894892 -0.03044751 -0.7556644 ]
 [-0.52600063  0.69813243  0.14909883]]
Taxa percentual de crecimento: -5.51979873395116
Taxa percentual de crecimento: -781047.40064608
Taxa percentual de crecimento: -2436.7347278639104


# Referências
- Anton, Howard Rorres, Chris. Álgebra Linear com Aplicações. Editora Bookman - 2012.

- Carl D, Meyer, Matrix Analysis and Applied Linear Algebra, Editora SIAM - 2000  

- Fuad Aleskerov • Hasan Ersel Dmitri Piontkovski, Linear Algebra for Economists, Editora Springer, 2011. 