<a href="https://colab.research.google.com/github/lcbjrrr/quant/blob/master/%C3%81lgebra_Linear_aplicada_a_um_problema_de_equil%C3%ADbrio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ficha Técnica

Disciplina:  - Algebra linear e Processos Dinâmicos.

Conteúdo: 

- Representação matricial

- Operações com linhas em matrizes.

- Matrizes elementares

- Solução de sistemas Lineares

Aplicação: 
- Aplicação em um problema de oferta e demanda. 

Autores: 
- Anderson Borba (anderson.aborba@professores.ibmec.edu.br) e
- Luiz Barboza (luiz.cbjunior@professores.ibmec.edu.br).

Endereço eletrônico: http://quant-ibmec.group/calculos/

# Sistemas de equações lineares:
Um sistema linear com $m$ equações e $n$ incógnitas modela o problema de uma economia com $n$ bens.

Equações lineares representando a demanda:
\begin{equation}\nonumber
    \left\{
    \begin{array}{ccccccccccc}
        a_{11}p_1&+& a_{12}p_2&+& \cdots&+& a_{1n}p_{n}&+&y_1Y&=&q_1^d \\
        a_{21}p_1&+& a_{22}p_2&+& \cdots&+& a_{2n}p_{n}&+&y_2Y&=&q_2^d \\
        \vdots & \vdots& &&&& & &\vdots &&\vdots \\
        a_{m1}p_1&+& a_{m2}p_2&+& \cdots&+& a_{mn}p_{n}&+&y_mY&=&q_m^d \\
    \end{array}
    \right.
\end{equation}

Equações lineares representando a oferta:

\begin{equation}\nonumber
    \left\{
    \begin{array}{ccc}
        b_{11}p_1+ c_0^1&=&q_1^s \\
        b_{21}p_2+ c_0^2&=&q_2^s \\
        \vdots &&\vdots \\
        b_{m1}p_3+ c_0^m&=&q_m^s \\
    \end{array}
    \right.
\end{equation}

A solução do sistema linear é uma $n-$upla de números $(p_1,p_2,\cdots,p_n)$ que satisfaça simultaneamento as $m$ equações nos dois sistemas lineares. No equilíbrio a demanda é igual a oferta para esse tipo de economia. Y representa a renda.

# Exemplo:
Considere uma economia com três bens $(q_1, q_2, q_3)$. Onde $Y$ representa a renda:

Equações lineares representando a demanda:
\begin{equation}\nonumber
    \left\{
    \begin{array}{cccccccccc}
         -0.05p_1&+& 0.02p_2&-& 0.01p_3&+&0.02Y&=& q_1^d\\
          0.01p_1&-& 0.04p_2&+& 0.01p_3&+&0.04Y&=& q_2^d\\
         -0.03p_1&+& 0.02p_2&-& 0.06p_3&+&0.01Y &=& q_3^d\\
    \end{array}
    \right.,
    \left[
    \begin{array}{rrr}
        -0.05&  0.02&  -0.01\\
        0.01&  -0.04&  0.01\\
        -0.03& 0.02& -0.06\\
    \end{array}
    \right]\left[
    \begin{array}{r}
        p_1\\
        p_2\\
        p_3\\
    \end{array}
    \right] +
    \left[
    \begin{array}{r}
        0.02Y\\
        0.04Y\\
        0.01Y\\
    \end{array}
    \right]
    =
       \left[
    \begin{array}{r}
        q_1^d\\
        q_2^d\\
        q_3^d\\
    \end{array}
    \right]
\end{equation}

Equações lineares representando a oferta:
\begin{equation}\nonumber
    \left\{
    \begin{array}{ccccc}
          0.2p_1&-&20 &=& q_1^s\\
          0.3p_2&-&14 &=& q_2^s\\
          0.1p_3&-&25 &=& q_3^s\\
    \end{array}
    \right.,
    \left[
    \begin{array}{rrr}
        0.2&  0  &  0  \\
        0  &  0.3&  0  \\
        0  & 0   &  0.1\\
    \end{array}
    \right]=
    \left[
    \begin{array}{r}
        q_1^s + 20\\
        q_2^s + 14\\
        q_3^s + 25\\
    \end{array}
    \right]
\end{equation}

Usando os seguintes fatos: na condição de equílibrio, a demanda é igual a oferta, e a renda é igual $Y=1000$. O sistema linear pode ser reescrito da seguinte forma:
\begin{equation}\nonumber
    \left\{
    \begin{array}{ccccccccccccc}
         -0.05p_1&+& 0.02p_2&-& 0.01p_3&+&0.02Y&=&0.2p_1&-&20  \\
          0.01p_1&-& 0.04p_2&+& 0.01p_3&+&0.04Y&=& 0.3p_2&-&14\\
         -0.03p_1&+& 0.02p_2&-& 0.06p_3&+&0.01Y &=& 0.1p_3&-&25\\
    \end{array}
    \right.,
\end{equation}
\begin{equation}\nonumber
    \left[
    \begin{array}{rrr}
        -0.05&  0.02&  -0.01\\
        0.01&  -0.04&  0.01\\
        -0.03& 0.02& -0.06\\
    \end{array}
    \right]
    \left[
    \begin{array}{r}
        p_1\\
        p_2\\
        p_3\\
    \end{array}
    \right]+
    \left[
    \begin{array}{r}
        0.02Y\\
        0.04Y\\
        0.01Y\\
    \end{array}
    \right]
    =
    \left[
    \begin{array}{rrr}
        0.2&  0  &  0  \\
        0  &  0.3&  0  \\
        0  & 0   &  0.1\\
    \end{array}
    \right]
    \left[
    \begin{array}{r}
        p_1\\
        p_2\\
        p_3\\
    \end{array}
    \right]-
    \left[
    \begin{array}{r}
        20\\
        14\\
        25\\
    \end{array}
    \right].
\end{equation}

Definindo:
\begin{equation}\nonumber
    A = \left[
    \begin{array}{rrr}
        -0.05&  0.02&  -0.01\\
        0.01&  -0.04&  0.01\\
        -0.03& 0.02& -0.06\\
    \end{array}
    \right],
\end{equation}
\begin{equation}\nonumber
    B = \left[
    \begin{array}{rrr}
        0.2&  0  &  0  \\
        0  &  0.3&  0  \\
        0  & 0   &  0.1\\
    \end{array}
    \right],
    \end{equation}
\begin{equation}\nonumber
    p = \left[
    \begin{array}{r}
        p_1\\
        p_2\\
        p_3\\
    \end{array}
    \right],
\end{equation}

\begin{equation}\nonumber
\hat{Y}=\left[\begin{array}{r}
        0.02Y\\
        0.04Y\\
        0.01Y\\
    \end{array}
    \right],
\end{equation}
e
\begin{equation}\nonumber
d=\left[\begin{array}{r}
        20\\
        14\\
        25\\
    \end{array}
    \right].
\end{equation}

O problema pode ser interpretado da seguinte maneira,
$$Ap+\hat{Y}=Bp-d,$$
ou 
$$Ap-Bp=-\hat{Y}-d,$$
ou ainda,
$$Bp-Ap=\hat{Y} + d,$$
então
$$(B-A)p=\hat{Y} + d.$$

Podemos encontrar os preço de equílibrio $p$ invertendo a matriz $(B-A)$, isto é,
$$p=(B-A)^{-1}(\hat{Y}+d).$$

Para resumir a notação definimos $F=B-A$ e $g=(\hat{Y}+d)$, e reescrevemos:
$$p=F^{-1}g$$


### Resultado numérico
Definindo F e g:

In [ ]:
import numpy as np
A = np.array([[-0.05, 0.02,  -0.01],[0.01,  -0.04,  0.01],[ -0.03, 0.02, -0.06]])
B = np.array([[0.2, 0,  0],[0,  0.3,  0],[ 0, 0, 0.1]])
print(A)
print(B)
F = B - A
print(F)

[[-0.05  0.02 -0.01]
 [ 0.01 -0.04  0.01]
 [-0.03  0.02 -0.06]]
[[0.2 0.  0. ]
 [0.  0.3 0. ]
 [0.  0.  0.1]]
[[ 0.25 -0.02  0.01]
 [-0.01  0.34 -0.01]
 [ 0.03 -0.02  0.16]]


In [ ]:
# Definição da renda
Y = 1000
YH = np.array([[0.02],[0.04],[0.01]])
YH = Y * YH
print(YH) 
# Vetor demanda
d = np.array([[20],[14],[25]])
print(d)
# Vetor lado direito
g = YH + d
print(g) 

[[20.]
 [40.]
 [10.]]
[[20]
 [14]
 [25]]
[[40.]
 [54.]
 [35.]]


Eliminação gaussiana:

In [ ]:
# Matriz 
print(F)
# Lado direito
print(g)


[[ 0.25 -0.02  0.01]
 [-0.01  0.34 -0.01]
 [ 0.03 -0.02  0.16]]
[[40.]
 [54.]
 [35.]]


Definindo a matriz extendida:

In [ ]:
FE = np.array([[0.25, -0.02,  0.01, 40],[-0.01,  0.34,  -0.01, 54],[ 0.03, -0.02, 0.16, 35]])
print(FE)

[[ 2.5e-01 -2.0e-02  1.0e-02  4.0e+01]
 [-1.0e-02  3.4e-01 -1.0e-02  5.4e+01]
 [ 3.0e-02 -2.0e-02  1.6e-01  3.5e+01]]


Definindo a operação $L_2=>L_2-\frac{a_{21}}{a_{11}}L_1$.

In [ ]:
E1 = np.array([[1,0,0],[-FE[1,0]/FE[0,0],1,0],[0,0,1]])
print(E1)

[[1.   0.   0.  ]
 [0.04 1.   0.  ]
 [0.   0.   1.  ]]


In [ ]:
E1 @ FE

array([[ 2.500e-01, -2.000e-02,  1.000e-02,  4.000e+01],
       [ 0.000e+00,  3.392e-01, -9.600e-03,  5.560e+01],
       [ 3.000e-02, -2.000e-02,  1.600e-01,  3.500e+01]])

Definindo a operação $L_3=>L_3-\frac{a_{31}}{a_{11}}L_1$.

In [ ]:
E2 = np.array([[1,0,0],[0,1,0],[-FE[2,0]/FE[0,0],0,1]])
print(E2)

[[ 1.    0.    0.  ]
 [ 0.    1.    0.  ]
 [-0.12  0.    1.  ]]


In [ ]:
AUX = E2 @ E1 @ FE
print(AUX)


[[ 2.500e-01 -2.000e-02  1.000e-02  4.000e+01]
 [ 0.000e+00  3.392e-01 -9.600e-03  5.560e+01]
 [ 0.000e+00 -1.760e-02  1.588e-01  3.020e+01]]


Definindo a operação $L_3=>L_3-\frac{a_{32}}{a_{22}}L_2$.

In [ ]:
E3 = np.array([[1,0,0],[0,1,0],[0,-AUX[2,1]/AUX[1,1],1]])
print(E3)

[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.05188679 1.        ]]


In [ ]:
E = E3 @ E2 @ E1
print(E)

[[ 1.          0.          0.        ]
 [ 0.04        1.          0.        ]
 [-0.11792453  0.05188679  1.        ]]


In [ ]:
EQ = E @ FE
print(EQ)

[[ 2.50000000e-01 -2.00000000e-02  1.00000000e-02  4.00000000e+01]
 [ 0.00000000e+00  3.39200000e-01 -9.60000000e-03  5.56000000e+01]
 [ 0.00000000e+00  0.00000000e+00  1.58301887e-01  3.30849057e+01]]


Usamos a matriz equivalente E para encontrar o vetor solução aproximado $(p_1,p_2,p_3)$.

In [ ]:
p3=EQ[2,3]/EQ[2,2]
print(p3)

208.99880810488676


In [ ]:
p2= (EQ[1,3] - EQ[1,2] * p3) / EQ[1,1] 
print(p2)

169.83015494636473


In [ ]:
p1= (EQ[0,3] - EQ[0,2] * p3 - EQ[0,1] * p2) / EQ[0,0]
print(p1)

165.2264600715137


A solução numérica para o preço de equílibrio $(p_1,p_2,p_3)=(165.2264600715137,169.83015494636473,208.99880810488676)$.

Solução usando pacotes do Python:

a) Usando a matriz inversa:

In [ ]:
FINV = np.linalg.inv(F)
p= FINV @ g
print(p)


[[165.22646007]
 [169.83015495]
 [208.9988081 ]]


b) Usando o comando para a fatoração LU.

In [ ]:
from scipy.linalg import lu
per, L, U = lu(F)
print(L)
print(U)
print(L @ U)

[[ 1.          0.          0.        ]
 [-0.04        1.          0.        ]
 [ 0.12       -0.05188679  1.        ]]
[[ 0.25       -0.02        0.01      ]
 [ 0.          0.3392     -0.0096    ]
 [ 0.          0.          0.15830189]]
[[ 0.25 -0.02  0.01]
 [-0.01  0.34 -0.01]
 [ 0.03 -0.02  0.16]]


# Referências
- Anton, Howard Rorres, Chris. Álgebra Linear com Aplicações. Editora Bookman- 2012.
- Fuad Aleskerov, Hasan Ersel, Dmitri Piontkovski. Linear Algebra for Economists. Springer - 2011.
- https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/solving-linear-systems/